### PR TITLE
change ceil to round

### PR DESCRIPTION
**Pull request by craigstanton**
Removes the forecast bias towards warmer temperatures

### CODE REVIEW

**Comment by kinow** [comment]
Merged, thanks! Looking forward to refreshing the widget in the big screen to see how it will affect the temperature displayed throughout the day :-)

**Comment by kinow** [comment]
BTW, you should now have access to write to this repository now, so you can either send pull requests or just commit to it directly :)

**Comment by craigstanton** [comment]
It's taken me a while through completely not knowing ruby, but I have cobbled together a Niwa Ruby Widget that might be safer going forward if DashingJS had been abandoned. I still need to look through climicons to align our forecasts with their icons or embed an school like we do with NIWAWeather. But not that I am stuck in a car with a sleeping baby I can't do much on it at all.

**Comment by kinow** [comment]
Nice! Let me know when you have that in a GitHub repository and I'll give it some testing. At least the weather this weekend was good for hacking some code :-) 

> Widget that might be safer going forward if DashingJS had been abandoned.

+1

**Comment by craigstanton** [comment]
Should I start a new repo or do you want a pull/push to convert yours to Ruby? Still need to figure out the license stuff for using Niwa if it is going to go public.

**Comment by kinow** [comment]
> Should I start a new repo or do you want a pull/push to convert yours to Ruby?

I think it's better to start a new repo for the Ruby version, and leave this other one here in case someone else is running the Node.js version.

> Still need to figure out the license stuff for using Niwa if it is going to go public.

Good point. I still don't know what's going under the NIWA GitHub organization. We can also search for other code referencing NIWA in GitHub: https://github.com/search?p=1&q=NIWA&type=Repositories&utf8=%E2%9C%93

Maybe we can host code like this widgets, and some scientific tutorials..

**Pull request merged**
